#!/bin/bash
check-dotfiles () {
    pushd ~/.dotfiles > /dev/null
    if [[ -n "$(git status --porcelain)" ]]; then
        echo -e "\e[33;1mThe dotfiles repo has uncommitted changes:\e[0m"
        git status --short
    fi
    popd > /dev/null
}
check-dotfiles

new-key () {
    ssh-keygen -t ed25519 -a 512 -f ~/.ssh/id_ed25519
    echo -e "\e[36;1mPublic key:\e[0m"
    cat ~/.ssh/id_ed25519.pub
}

clone () {
    git clone git@github.com:$1.git
}

wttr() {
    local request="wttr.in/${1-Centralia,WA}?uF"
    [ "$(tput cols)" -lt 125 ] && request+='n'
    curl -H "Accept-Language: ${LANG%_*}" --compressed "$request"
}
